language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

services:
    - mysql
    - elasticsearch

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

env:
    global:
        - DK_DATABASE_HOST=127.0.0.1
        - DK_DATABASE_PASSWORD=null
        - DK_ELASTICSEARCH_HOST=127.0.0.1
        - DK_ELASTICSEARCH_PORT=9200

before_script:
    - cp var/jwt/private.pem.dist var/jwt/private.pem
    - cp var/jwt/public.pem.dist var/jwt/public.pem
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
    - composer self-update
    - composer install --no-interaction

script:
    - ./bin/run-tests
