app:
    image: iamluc/symfony
    container_name: dunkerque
    volumes:
        - .:/var/www/html
        # To speed up composer
        #- ~/.composer:/var/www/.composer

    environment:
        - DOCKER_ENV=dev
    ports:
        # Adapt to you need
        - 8000:80

    links:
        - mariadb:db
        - rabbitmq:rabbitmq
        - elasticsearch:elasticsearch

    # Uncomment lines below to enable Blackfire
    # You have to export env variables (BLACKFIRE_SERVER_ID and BLACKFIRE_SERVER_TOKEN) before running docker-compose
#        - blackfire:blackfire
#
#blackfire:
#    image: blackfire/blackfire
#    environment:
#        - BLACKFIRE_SERVER_ID
#        - BLACKFIRE_SERVER_TOKEN


phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dunkerque_phpmyadmin
    links:
        - mariadb:db

mariadb:
    image: mariadb:10
    environment:
        - MYSQL_ROOT_PASSWORD=dkpassword

rabbitmq:
    image: rabbitmq:3-management
    container_name: dunkerque_rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=dunkerque
        - RABBITMQ_DEFAULT_PASS=dkpassword
    ports:
        - 15672:15672

workerwebhook:
    image: iamluc/symfony
    volumes_from:
        - app
    links:
        - rabbitmq:rabbitmq
    environment:
        - SYMFONY_ENV=dev
    command: sleep 5 && app/console dunkerque:broker:setup && app/console swarrot:consume:webhook

elasticsearch:
    image: elasticsearch:1
    container_name: dunkerque_elasticsearch
    ports:
        - 9200:9200
